### ISSUE TITLE
run elasticsearch.bat error: "Could not reserve enough space for object heap"

### ISSUE THREAD

**Issue by d87335903** [d87335903/Elasticsearch_in_Action#1]
elasticsearch-5.0.0-alpha5,java version "1.7.0_67",Win 7 Professional

**Comment by d87335903** [comment]
Go to Start → Control Panel → System → Advanced system settings → advanced(tab) → Environment Variables → System Variables → New,Variable name: _JAVA_OPTIONS ,Variable value: -Xmx512M
refer to http://stackoverflow.com/questions/18040361/java-could-not-reserve-enough-space-for-object-heap-error

**Comment by prafulux** [comment]
# Installation for ElasticSearch
1) Comment entry in C:\ELK\elasticsearch-5.4.0\elasticsearch-5.4.0\config\jvm.options

#-Xms2g
#-Xmx2g

2) set  ES_JAVA_OPTS as below in elasticsearch.bat
set ES_JAVA_OPTS = "-Xms512m -Xmx512m"

**Comment by sheldonshen** [comment]
@prafulux ,Thanks,:smile:

**Comment by abhilashfancy** [comment]
thanks it worked perfectly
